package hh.game.mgba_android.tracker.tables

object ItemTable {

    private val items = arrayOfNulls<String>(377)

    init {
        // Pokeballs
        items[1]   = "Master Ball"
        items[2]   = "Ultra Ball"
        items[3]   = "Great Ball"
        items[4]   = "Poké Ball"
        items[5]   = "Safari Ball"
        items[6]   = "Net Ball"
        items[7]   = "Dive Ball"
        items[8]   = "Nest Ball"
        items[9]   = "Repeat Ball"
        items[10]  = "Timer Ball"
        items[11]  = "Luxury Ball"
        items[12]  = "Premier Ball"
        // Medicine
        items[13]  = "Potion"
        items[14]  = "Antidote"
        items[15]  = "Burn Heal"
        items[16]  = "Ice Heal"
        items[17]  = "Awakening"
        items[18]  = "Parlyz Heal"
        items[19]  = "Full Restore"
        items[20]  = "Max Potion"
        items[21]  = "Hyper Potion"
        items[22]  = "Super Potion"
        items[23]  = "Full Heal"
        items[24]  = "Revive"
        items[25]  = "Max Revive"
        items[26]  = "Fresh Water"
        items[27]  = "Soda Pop"
        items[28]  = "Lemonade"
        items[29]  = "Moomoo Milk"
        items[30]  = "EnergyPowder"
        items[31]  = "Energy Root"
        items[32]  = "Heal Powder"
        items[33]  = "Revival Herb"
        items[34]  = "Ether"
        items[35]  = "Max Ether"
        items[36]  = "Elixir"
        items[37]  = "Max Elixir"
        items[38]  = "Lava Cookie"
        items[39]  = "Blue Flute"
        items[40]  = "Yellow Flute"
        items[41]  = "Red Flute"
        items[42]  = "Black Flute"
        items[43]  = "White Flute"
        items[44]  = "Berry Juice"
        items[45]  = "Sacred Ash"
        items[46]  = "Shoal Salt"
        items[47]  = "Shoal Shell"
        items[48]  = "Red Shard"
        items[49]  = "Blue Shard"
        items[50]  = "Yellow Shard"
        items[51]  = "Green Shard"
        // 52-62 unused
        // Vitamins / stat items
        items[63]  = "HP Up"
        items[64]  = "Protein"
        items[65]  = "Iron"
        items[66]  = "Carbos"
        items[67]  = "Calcium"
        items[68]  = "Rare Candy"
        items[69]  = "PP Up"
        items[70]  = "Zinc"
        items[71]  = "PP Max"
        // 72 unused
        // Battle items
        items[73]  = "Guard Spec."
        items[74]  = "Dire Hit"
        items[75]  = "X Attack"
        items[76]  = "X Defend"
        items[77]  = "X Speed"
        items[78]  = "X Accuracy"
        items[79]  = "X Special"
        items[80]  = "Poké Doll"
        items[81]  = "Fluffy Tail"
        // 82 unused
        items[83]  = "Super Repel"
        items[84]  = "Max Repel"
        items[85]  = "Escape Rope"
        items[86]  = "Repel"
        // 87-92 unused
        // Evolution stones
        items[93]  = "Sun Stone"
        items[94]  = "Moon Stone"
        items[95]  = "Fire Stone"
        items[96]  = "Thunderstone"
        items[97]  = "Water Stone"
        items[98]  = "Leaf Stone"
        // 99-102 unused
        // Sellable items
        items[103] = "TinyMushroom"
        items[104] = "Big Mushroom"
        // 105 unused
        items[106] = "Pearl"
        items[107] = "Big Pearl"
        items[108] = "Stardust"
        items[109] = "Star Piece"
        items[110] = "Nugget"
        items[111] = "Heart Scale"
        // 112-120 unused
        // Mail
        items[121] = "Orange Mail"
        items[122] = "Harbor Mail"
        items[123] = "Glitter Mail"
        items[124] = "Mech Mail"
        items[125] = "Wood Mail"
        items[126] = "Wave Mail"
        items[127] = "Bead Mail"
        items[128] = "Shadow Mail"
        items[129] = "Tropic Mail"
        items[130] = "Dream Mail"
        items[131] = "Fab Mail"
        items[132] = "Retro Mail"
        // Berries
        items[133] = "Cheri Berry"
        items[134] = "Chesto Berry"
        items[135] = "Pecha Berry"
        items[136] = "Rawst Berry"
        items[137] = "Aspear Berry"
        items[138] = "Leppa Berry"
        items[139] = "Oran Berry"
        items[140] = "Persim Berry"
        items[141] = "Lum Berry"
        items[142] = "Sitrus Berry"
        items[143] = "Figy Berry"
        items[144] = "Wiki Berry"
        items[145] = "Mago Berry"
        items[146] = "Aguav Berry"
        items[147] = "Iapapa Berry"
        items[148] = "Razz Berry"
        items[149] = "Bluk Berry"
        items[150] = "Nanab Berry"
        items[151] = "Wepear Berry"
        items[152] = "Pinap Berry"
        items[153] = "Pomeg Berry"
        items[154] = "Kelpsy Berry"
        items[155] = "Qualot Berry"
        items[156] = "Hondew Berry"
        items[157] = "Grepa Berry"
        items[158] = "Tamato Berry"
        items[159] = "Cornn Berry"
        items[160] = "Magost Berry"
        items[161] = "Rabuta Berry"
        items[162] = "Nomel Berry"
        items[163] = "Spelon Berry"
        items[164] = "Pamtre Berry"
        items[165] = "Watmel Berry"
        items[166] = "Durin Berry"
        items[167] = "Belue Berry"
        items[168] = "Liechi Berry"
        items[169] = "Ganlon Berry"
        items[170] = "Salac Berry"
        items[171] = "Petaya Berry"
        items[172] = "Apicot Berry"
        items[173] = "Lansat Berry"
        items[174] = "Starf Berry"
        items[175] = "Enigma Berry"
        // 176-178 unused
        // Held items
        items[179] = "BrightPowder"
        items[180] = "White Herb"
        items[181] = "Macho Brace"
        items[182] = "Exp. Share"
        items[183] = "Quick Claw"
        items[184] = "Soothe Bell"
        items[185] = "Mental Herb"
        items[186] = "Choice Band"
        items[187] = "King's Rock"
        items[188] = "SilverPowder"
        items[189] = "Amulet Coin"
        items[190] = "Cleanse Tag"
        items[191] = "Soul Dew"
        items[192] = "DeepSeaTooth"
        items[193] = "DeepSeaScale"
        items[194] = "Smoke Ball"
        items[195] = "Everstone"
        items[196] = "Focus Band"
        items[197] = "Lucky Egg"
        items[198] = "Scope Lens"
        items[199] = "Metal Coat"
        items[200] = "Leftovers"
        items[201] = "Dragon Scale"
        items[202] = "Light Ball"
        items[203] = "Soft Sand"
        items[204] = "Hard Stone"
        items[205] = "Miracle Seed"
        items[206] = "BlackGlasses"
        items[207] = "Black Belt"
        items[208] = "Magnet"
        items[209] = "Mystic Water"
        items[210] = "Sharp Beak"
        items[211] = "Poison Barb"
        items[212] = "NeverMeltIce"
        items[213] = "Spell Tag"
        items[214] = "TwistedSpoon"
        items[215] = "Charcoal"
        items[216] = "Dragon Fang"
        items[217] = "Silk Scarf"
        items[218] = "Up-Grade"
        items[219] = "Shell Bell"
        items[220] = "Sea Incense"
        items[221] = "Lax Incense"
        items[222] = "Lucky Punch"
        items[223] = "Metal Powder"
        items[224] = "Thick Club"
        items[225] = "Stick"
        // 226-253 unused
        // Contest scarves
        items[254] = "Red Scarf"
        items[255] = "Blue Scarf"
        items[256] = "Pink Scarf"
        items[257] = "Green Scarf"
        items[258] = "Yellow Scarf"
        // Key items
        items[259] = "Mach Bike"
        items[260] = "Coin Case"
        items[261] = "Itemfinder"
        items[262] = "Old Rod"
        items[263] = "Good Rod"
        items[264] = "Super Rod"
        items[265] = "S.S. Ticket"
        items[266] = "Contest Pass"
        // 267 unused
        items[268] = "Wailmer Pail"
        items[269] = "Devon Goods"
        items[270] = "Soot Sack"
        items[271] = "Basement Key"
        items[272] = "Acro Bike"
        items[273] = "Pokéblock Case"
        items[274] = "Letter"
        items[275] = "Eon Ticket"
        items[276] = "Red Orb"
        items[277] = "Blue Orb"
        items[278] = "Scanner"
        items[279] = "Go-Goggles"
        items[280] = "Meteorite"
        items[281] = "Rm. 1 Key"
        items[282] = "Rm. 2 Key"
        items[283] = "Rm. 4 Key"
        items[284] = "Rm. 6 Key"
        items[285] = "Storage Key"
        items[286] = "Root Fossil"
        items[287] = "Claw Fossil"
        items[288] = "Devon Scope"
        // TMs
        items[289] = "TM01"
        items[290] = "TM02"
        items[291] = "TM03"
        items[292] = "TM04"
        items[293] = "TM05"
        items[294] = "TM06"
        items[295] = "TM07"
        items[296] = "TM08"
        items[297] = "TM09"
        items[298] = "TM10"
        items[299] = "TM11"
        items[300] = "TM12"
        items[301] = "TM13"
        items[302] = "TM14"
        items[303] = "TM15"
        items[304] = "TM16"
        items[305] = "TM17"
        items[306] = "TM18"
        items[307] = "TM19"
        items[308] = "TM20"
        items[309] = "TM21"
        items[310] = "TM22"
        items[311] = "TM23"
        items[312] = "TM24"
        items[313] = "TM25"
        items[314] = "TM26"
        items[315] = "TM27"
        items[316] = "TM28"
        items[317] = "TM29"
        items[318] = "TM30"
        items[319] = "TM31"
        items[320] = "TM32"
        items[321] = "TM33"
        items[322] = "TM34"
        items[323] = "TM35"
        items[324] = "TM36"
        items[325] = "TM37"
        items[326] = "TM38"
        items[327] = "TM39"
        items[328] = "TM40"
        items[329] = "TM41"
        items[330] = "TM42"
        items[331] = "TM43"
        items[332] = "TM44"
        items[333] = "TM45"
        items[334] = "TM46"
        items[335] = "TM47"
        items[336] = "TM48"
        items[337] = "TM49"
        items[338] = "TM50"
        // HMs
        items[339] = "HM01"
        items[340] = "HM02"
        items[341] = "HM03"
        items[342] = "HM04"
        items[343] = "HM05"
        items[344] = "HM06"
        items[345] = "HM07"
        items[346] = "HM08"
        // 347-348 unused
        // FireRed/LeafGreen key items
        items[349] = "Oak's Parcel"
        items[350] = "Poké Flute"
        items[351] = "Secret Key"
        items[352] = "Bike Voucher"
        items[353] = "Gold Teeth"
        items[354] = "Old Amber"
        items[355] = "Card Key"
        items[356] = "Lift Key"
        items[357] = "Helix Fossil"
        items[358] = "Dome Fossil"
        items[359] = "Silph Scope"
        items[360] = "Bicycle"
        items[361] = "Town Map"
        items[362] = "Vs. Seeker"
        items[363] = "Fame Checker"
        items[364] = "TM Case"
        items[365] = "Berry Pouch"
        items[366] = "Teachy TV"
        items[367] = "Tri-Pass"
        items[368] = "Rainbow Pass"
        items[369] = "Tea"
        items[370] = "MysticTicket"
        items[371] = "AuroraTicket"
        items[372] = "Powder Jar"
        items[373] = "Ruby"
        items[374] = "Sapphire"
        items[375] = "Magma Emblem"
        items[376] = "Old Sea Map"
    }

    fun get(itemId: Int): String {
        if (itemId < 1 || itemId > 376) return "???"
        return items[itemId] ?: "???"
    }
}
