package hh.game.mgba_android.tracker.ds.tables

/**
 * Gen IV ability names and descriptions (ability IDs 1-123).
 * Gen IV added abilities 77-123 to the Gen III set.
 */
object GenIVAbilityTable {
    data class AbilityInfo(val name: String, val description: String)

    private val ABILITIES = mapOf(
        1  to AbilityInfo("Stench",          "May cause flinching when hitting."),
        2  to AbilityInfo("Drizzle",         "Summons rain on entry."),
        3  to AbilityInfo("Speed Boost",     "Speed rises each turn."),
        4  to AbilityInfo("Battle Armor",    "Protected from critical hits."),
        5  to AbilityInfo("Sturdy",          "One-hit KO moves fail."),
        6  to AbilityInfo("Damp",            "Prevents explosion moves."),
        7  to AbilityInfo("Limber",          "Cannot be paralyzed."),
        8  to AbilityInfo("Sand Veil",       "Evasion up in sandstorm."),
        9  to AbilityInfo("Static",          "May paralyze on contact."),
        10 to AbilityInfo("Volt Absorb",     "Restores HP when hit by Electric."),
        11 to AbilityInfo("Water Absorb",    "Restores HP when hit by Water."),
        12 to AbilityInfo("Oblivious",       "Cannot be infatuated."),
        13 to AbilityInfo("Cloud Nine",      "Eliminates weather effects."),
        14 to AbilityInfo("Compoundeyes",    "Accuracy raised by 30%."),
        15 to AbilityInfo("Insomnia",        "Cannot fall asleep."),
        16 to AbilityInfo("Color Change",    "Type changes to move's type."),
        17 to AbilityInfo("Immunity",        "Cannot be poisoned."),
        18 to AbilityInfo("Flash Fire",      "Powers up Fire moves when hit by Fire."),
        19 to AbilityInfo("Shield Dust",     "Blocks secondary effects."),
        20 to AbilityInfo("Own Tempo",       "Cannot be confused."),
        21 to AbilityInfo("Suction Cups",    "Cannot be forced to switch."),
        22 to AbilityInfo("Intimidate",      "Lowers foe's Attack on entry."),
        23 to AbilityInfo("Shadow Tag",      "Prevents foe from fleeing."),
        24 to AbilityInfo("Rough Skin",      "Damages attacker on contact."),
        25 to AbilityInfo("Wonder Guard",    "Only super-effective moves land."),
        26 to AbilityInfo("Levitate",        "Immune to Ground moves."),
        27 to AbilityInfo("Effect Spore",    "May inflict status on contact."),
        28 to AbilityInfo("Synchronize",     "Passes status to the attacker."),
        29 to AbilityInfo("Clear Body",      "Stats cannot be lowered by foes."),
        30 to AbilityInfo("Natural Cure",    "Status heals on switching out."),
        31 to AbilityInfo("Lightning Rod",   "Draws Electric moves; raises SpAtk."),
        32 to AbilityInfo("Serene Grace",    "Doubles secondary effect chance."),
        33 to AbilityInfo("Swift Swim",      "Speed doubles in rain."),
        34 to AbilityInfo("Chlorophyll",     "Speed doubles in sun."),
        35 to AbilityInfo("Illuminate",      "Raises wild encounter rate."),
        36 to AbilityInfo("Trace",           "Copies foe's ability on entry."),
        37 to AbilityInfo("Huge Power",      "Attack stat doubled."),
        38 to AbilityInfo("Poison Point",    "May poison on contact."),
        39 to AbilityInfo("Inner Focus",     "Cannot flinch."),
        40 to AbilityInfo("Magma Armor",     "Cannot be frozen."),
        41 to AbilityInfo("Water Veil",      "Cannot be burned."),
        42 to AbilityInfo("Magnet Pull",     "Prevents Steel-types from fleeing."),
        43 to AbilityInfo("Soundproof",      "Unaffected by sound moves."),
        44 to AbilityInfo("Rain Dish",       "Restores HP in rain."),
        45 to AbilityInfo("Sand Stream",     "Summons sandstorm on entry."),
        46 to AbilityInfo("Pressure",        "Foe uses 2 PP per move."),
        47 to AbilityInfo("Thick Fat",       "Halves damage from Fire and Ice."),
        48 to AbilityInfo("Early Bird",      "Wakes from sleep faster."),
        49 to AbilityInfo("Flame Body",      "May burn on contact."),
        50 to AbilityInfo("Run Away",        "Always flee from wild Pokemon."),
        51 to AbilityInfo("Keen Eye",        "Accuracy cannot be lowered."),
        52 to AbilityInfo("Hustle",          "Boosts Attack; lowers accuracy."),
        53 to AbilityInfo("Cute Charm",      "May infatuate on contact."),
        54 to AbilityInfo("Plus",            "Raises SpAtk with a partner."),
        55 to AbilityInfo("Minus",           "Raises SpAtk with a partner."),
        56 to AbilityInfo("Forecast",        "Changes type with weather."),
        57 to AbilityInfo("Sticky Hold",     "Item cannot be removed."),
        58 to AbilityInfo("Shed Skin",       "May heal status each turn."),
        59 to AbilityInfo("Guts",            "Attack raised when statused."),
        60 to AbilityInfo("Marvel Scale",    "Defense raised when statused."),
        61 to AbilityInfo("Liquid Ooze",     "Damages HP-draining foes."),
        62 to AbilityInfo("Overgrow",        "Powers up Grass moves at low HP."),
        63 to AbilityInfo("Torrent",         "Powers up Water moves at low HP."),
        64 to AbilityInfo("Blaze",           "Powers up Fire moves at low HP."),
        65 to AbilityInfo("Overgrow",        "Powers up Grass moves at low HP."),
        66 to AbilityInfo("Blaze",           "Powers up Fire moves at low HP."),
        67 to AbilityInfo("Torrent",         "Powers up Water moves at low HP."),
        68 to AbilityInfo("Swarm",           "Powers up Bug moves at low HP."),
        69 to AbilityInfo("Rock Head",       "No recoil from recoil moves."),
        70 to AbilityInfo("Drought",         "Summons harsh sunlight on entry."),
        71 to AbilityInfo("Arena Trap",      "Prevents foe from fleeing."),
        72 to AbilityInfo("Vital Spirit",    "Cannot fall asleep."),
        73 to AbilityInfo("White Smoke",     "Stats cannot be lowered."),
        74 to AbilityInfo("Pure Power",      "Attack stat doubled."),
        75 to AbilityInfo("Shell Armor",     "Protected from critical hits."),
        76 to AbilityInfo("Air Lock",        "Eliminates weather effects."),
        // Gen IV new abilities
        77 to AbilityInfo("Tangled Feet",    "Evasion rises when confused."),
        78 to AbilityInfo("Motor Drive",     "Speed rises when hit by Electric."),
        79 to AbilityInfo("Rivalry",         "Power varies by gender match."),
        80 to AbilityInfo("Steadfast",       "Speed rises when flinched."),
        81 to AbilityInfo("Snow Cloak",      "Evasion up in hail."),
        82 to AbilityInfo("Gluttony",        "Uses Berry at 50% HP."),
        83 to AbilityInfo("Anger Point",     "Maxes Attack after a critical hit."),
        84 to AbilityInfo("Unburden",        "Speed doubles after losing item."),
        85 to AbilityInfo("Heatproof",       "Halves damage from Fire moves."),
        86 to AbilityInfo("Simple",          "Stat changes are doubled."),
        87 to AbilityInfo("Dry Skin",        "Heals in rain; hurt by sun/Fire."),
        88 to AbilityInfo("Download",        "Raises Atk or SpAtk based on foe."),
        89 to AbilityInfo("Iron Fist",       "Powers up punching moves."),
        90 to AbilityInfo("Poison Heal",     "Restores HP when poisoned."),
        91 to AbilityInfo("Adaptability",    "STAB bonus raised to 2×."),
        92 to AbilityInfo("Skill Link",      "Multi-hit moves always hit max times."),
        93 to AbilityInfo("Hydration",       "Heals status conditions in rain."),
        94 to AbilityInfo("Solar Power",     "SpAtk raises in sun; HP drains."),
        95 to AbilityInfo("Quick Feet",      "Speed raises when statused."),
        96 to AbilityInfo("Normalize",       "All moves become Normal type."),
        97 to AbilityInfo("Sniper",          "Critical hits deal 3× damage."),
        98 to AbilityInfo("Magic Guard",     "Only damaged by direct attacks."),
        99 to AbilityInfo("No Guard",        "All moves hit regardless of accuracy."),
        100 to AbilityInfo("Stall",          "Always moves last."),
        101 to AbilityInfo("Technician",     "Powers up weak moves."),
        102 to AbilityInfo("Leaf Guard",     "No status conditions in sun."),
        103 to AbilityInfo("Klutz",          "Cannot use held items."),
        104 to AbilityInfo("Mold Breaker",   "Ignores foe's ability."),
        105 to AbilityInfo("Super Luck",     "Critical hit rate raised."),
        106 to AbilityInfo("Aftermath",      "Damages attacker on KO."),
        107 to AbilityInfo("Anticipation",   "Senses dangerous moves."),
        108 to AbilityInfo("Forewarn",       "Senses foe's strongest move."),
        109 to AbilityInfo("Unaware",        "Ignores foe's stat changes."),
        110 to AbilityInfo("Tinted Lens",    "Powers up not-very-effective moves."),
        111 to AbilityInfo("Filter",         "Reduces super-effective damage."),
        112 to AbilityInfo("Slow Start",     "Atk and Speed halved for 5 turns."),
        113 to AbilityInfo("Scrappy",        "Normal/Fighting hit Ghost-types."),
        114 to AbilityInfo("Storm Drain",    "Draws Water moves; raises SpAtk."),
        115 to AbilityInfo("Ice Body",       "Restores HP in hail."),
        116 to AbilityInfo("Solid Rock",     "Reduces super-effective damage."),
        117 to AbilityInfo("Snow Warning",   "Summons hail on entry."),
        118 to AbilityInfo("Honey Gather",   "May collect Honey after battle."),
        119 to AbilityInfo("Frisk",          "Senses foe's held item."),
        120 to AbilityInfo("Reckless",       "Powers up recoil moves."),
        121 to AbilityInfo("Multitype",      "Type changes with held Plate."),
        122 to AbilityInfo("Flower Gift",    "Raises Atk/SpDef in sun."),
        123 to AbilityInfo("Bad Dreams",     "Damages sleeping foes each turn."),
    )

    fun getName(id: Int): String = ABILITIES[id]?.name ?: "???"
    fun getDescription(id: Int): String = ABILITIES[id]?.description ?: ""
    fun get(id: Int): AbilityInfo? = ABILITIES[id]
}
